version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  randomnamespace:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: test package manager

