
version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  pre-deployment:     
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - run:
          command: npm run build 4
          name: start build
