
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  pre-deployment:
    executor: node/default
    steps:
      - checkout
      - run:
          command: |
            npm install
          name: install node modules
      - run:
          command: |
            npm run lint
          name: check eslint -- type strict
  # deployment-to-vercel:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - run: 
  #         command: 

          

workflows:
  main:     
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - pre-deployment
          


