version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  pre-deployment: 
    jobs:
      - node/test:
          filters:
            branches: 
              only:
                - main
              version: '16.10'
              pkg-manager: npm
